// This file is generated by Ember Desktop.  Please do not edit manually.
//
//

// Enclosing macro to prevent multiple inclusion
#ifndef __BLE_SOC_EVENTS__
#define __BLE_SOC_EVENTS__


// Generated events.
#include <stdint.h>
#include <stddef.h>
#include CONFIGURATION_HEADER
#include "event_control.h"


void advSetup(void);
extern EmberEventControl advTimerEvt;

void appUiTick(void);
extern EmberEventControl uiTimerEvt;

void hidSendKeyboardText(void);
extern EmberEventControl hidTimerEvt;



const EmberEventData emAppEvents[] = {
  {&advTimerEvt, advSetup},
  {&uiTimerEvt, appUiTick},
  {&hidTimerEvt, hidSendKeyboardText},
  {NULL, NULL}
};
#endif // __BLE_SOC_EVENTS__
