// This file is generated by Ember Desktop.  Please do not edit manually.
//
//

// Enclosing macro to prevent multiple inclusion
#ifndef __BLE_SOC_CONFIG__
#define __BLE_SOC_CONFIG__




// Top level macros
#define SILABS_AF_DEVICE_NAME "ble-soc"


// Generated plugin macros

// Use this macro to check if Advertisement plugin is included
#define SILABS_AF_PLUGIN_ADVERTISEMENT
// User options for plugin Advertisement
#define SILABS_AF_PLUGIN_ADVERTISEMENT_ADV_INT_MIN1 30
#define SILABS_AF_PLUGIN_ADVERTISEMENT_ADV_INT_MAX1 60
#define SILABS_AF_PLUGIN_ADVERTISEMENT_ADV_TIME1 30
#define ADV_GENERAL_DISCOVERABLE 1
#define ADV_LIMITED_DISCOVERABLE 2
#define SILABS_AF_PLUGIN_ADVERTISEMENT_ADV_TYPE1 ADV_GENERAL_DISCOVERABLE
#define SILABS_AF_PLUGIN_ADVERTISEMENT_ADV_INT_MIN2 1000
#define SILABS_AF_PLUGIN_ADVERTISEMENT_ADV_INT_MAX2 1200
#define SILABS_AF_PLUGIN_ADVERTISEMENT_ADV_TIME2 120
#define ADV_GENERAL_DISCOVERABLE 1
#define ADV_LIMITED_DISCOVERABLE 2
#define SILABS_AF_PLUGIN_ADVERTISEMENT_ADV_TYPE2 ADV_GENERAL_DISCOVERABLE

// Use this macro to check if Bluetooth Smart Demo Application plugin is included
#define SILABS_AF_PLUGIN_APP

// Use this macro to check if Bluetooth Smart Demo Application Hardware Abstraction plugin is included
#define SILABS_AF_PLUGIN_APP_HW

// Use this macro to check if Connection plugin is included
#define SILABS_AF_PLUGIN_CONNECTION
// User options for plugin Connection
#define SILABS_AF_PLUGIN_CONNECTION_CON_PAIRING
#define SILABS_AF_PLUGIN_CONNECTION_CON_BONDING

// Use this macro to check if Device Information plugin is included
#define SILABS_AF_PLUGIN_DEVICE_INFO
// User options for plugin Device Information
#define SILABS_AF_PLUGIN_DEVICE_INFO_MAN_NAME_STRING_EN
#define SILABS_AF_PLUGIN_DEVICE_INFO_MAN_NAME_STRING "Silicon Labs"
#define SILABS_AF_PLUGIN_DEVICE_INFO_MAN_NAME_STRING_LENGTH (12)
#define SILABS_AF_PLUGIN_DEVICE_INFO_MOD_NUM_STRING_EN
#define SILABS_AF_PLUGIN_DEVICE_INFO_MOD_NUM_STRING "1.0"
#define SILABS_AF_PLUGIN_DEVICE_INFO_MOD_NUM_STRING_LENGTH (3)
#define SILABS_AF_PLUGIN_DEVICE_INFO_SER_NUM_STRING_EN
#define SILABS_AF_PLUGIN_DEVICE_INFO_SER_NUM_STRING "ffff"
#define SILABS_AF_PLUGIN_DEVICE_INFO_SER_NUM_STRING_LENGTH (4)
#define SILABS_AF_PLUGIN_DEVICE_INFO_HW_REV_STRING_EN
#define SILABS_AF_PLUGIN_DEVICE_INFO_HW_REV_STRING "ffff"
#define SILABS_AF_PLUGIN_DEVICE_INFO_HW_REV_STRING_LENGTH (4)
#define SILABS_AF_PLUGIN_DEVICE_INFO_FW_REV_STRING_EN
#define SILABS_AF_PLUGIN_DEVICE_INFO_FW_REV_STRING "ffff"
#define SILABS_AF_PLUGIN_DEVICE_INFO_FW_REV_STRING_LENGTH (4)
#define SILABS_AF_PLUGIN_DEVICE_INFO_SW_REV_STRING_EN
#define SILABS_AF_PLUGIN_DEVICE_INFO_SW_REV_STRING "ffff"
#define SILABS_AF_PLUGIN_DEVICE_INFO_SW_REV_STRING_LENGTH (4)
#define SILABS_AF_PLUGIN_DEVICE_INFO_SYS_ID_EN
#define SILABS_AF_PLUGIN_DEVICE_INFO_SYS_ID "ffffffffffffffff"
#define SILABS_AF_PLUGIN_DEVICE_INFO_SYS_ID_LENGTH (16)
#define SILABS_AF_PLUGIN_DEVICE_INFO_REG_CERT_D_L_EN
#define SILABS_AF_PLUGIN_DEVICE_INFO_REG_CERT_D_L "ffff"
#define SILABS_AF_PLUGIN_DEVICE_INFO_REG_CERT_D_L_LENGTH (4)
#define SILABS_AF_PLUGIN_DEVICE_INFO_PNP_ID_EN
#define SILABS_AF_PLUGIN_DEVICE_INFO_PNP_ID "01ffffffffffff"
#define SILABS_AF_PLUGIN_DEVICE_INFO_PNP_ID_LENGTH (14)

// Use this macro to check if GAP plugin is included
#define SILABS_AF_PLUGIN_GAP
// User options for plugin GAP
#define GAP_UNKNOWN 0
#define GAP_GENERIC_THERMOMETER 3
#define GAP_HR_SENSOR 4003
#define GAP_KEYBOARD C103
#define GAP_CSC_SENSOR 8504
#define GAP_CSP 8404
#define SILABS_AF_PLUGIN_GAP_DEV_APPEARANCE GAP_UNKNOWN

// Use this macro to check if Human Interface Device plugin is included
#define SILABS_AF_PLUGIN_HID
// User options for plugin Human Interface Device
#define SILABS_AF_PLUGIN_HID_HID_TEXT "This is a demonstration of Bluetooth Low Energy HID profile.\n"
#define SILABS_AF_PLUGIN_HID_HID_TEXT_LENGTH (62)

// Use this macro to check if Idle/Sleep plugin is included
#define SILABS_AF_PLUGIN_IDLE_SLEEP
// User options for plugin Idle/Sleep
#define SILABS_AF_PLUGIN_IDLE_SLEEP_MINIMUM_DURATION_MS 5

// Use this macro to check if Bluetooth Smart Platform plugin is included
#define SILABS_AF_PLUGIN_PLATFORM

// Use this macro to check if Bluetooth Smart Platform Hardware Abstraction plugin is included
#define SILABS_AF_PLUGIN_PLATFORM_HW


// Generated API headers

// API app_hw from Bluetooth Smart Demo Application Hardware Abstraction plugin
#define SILABS_AF_API_APP_HW "../../../../../SiliconLabs/BluetoothSmartSDK/1.0.2.0-GA/sdk/plugins/app_hw/app_hw.h"


// Custom macros
#ifdef EMBER_AF_RADIO
#undef EMBER_AF_RADIO
#endif
#define EMBER_AF_RADIO EFR32

#ifdef EMBER_AF_RADIO_FULL
#undef EMBER_AF_RADIO_FULL
#endif
#define EMBER_AF_RADIO_FULL EFR32BG1B232F256GM32

#ifdef EMBER_AF_RADIO_FAMILY
#undef EMBER_AF_RADIO_FAMILY
#endif
#define EMBER_AF_RADIO_FAMILY B

#ifdef EMBER_AF_RADIO_PERFORMANCE
#undef EMBER_AF_RADIO_PERFORMANCE
#endif
#define EMBER_AF_RADIO_PERFORMANCE B

#ifdef EMBER_AF_RADIO_RADIO
#undef EMBER_AF_RADIO_RADIO
#endif
#define EMBER_AF_RADIO_RADIO 232

#ifdef EMBER_AF_RADIO_FLASH
#undef EMBER_AF_RADIO_FLASH
#endif
#define EMBER_AF_RADIO_FLASH 256K

#ifdef EMBER_AF_RADIO_TEMP
#undef EMBER_AF_RADIO_TEMP
#endif
#define EMBER_AF_RADIO_TEMP G

#ifdef EMBER_AF_RADIO_PACKAGE
#undef EMBER_AF_RADIO_PACKAGE
#endif
#define EMBER_AF_RADIO_PACKAGE M

#ifdef EMBER_AF_RADIO_PINS
#undef EMBER_AF_RADIO_PINS
#endif
#define EMBER_AF_RADIO_PINS 32

#ifdef EMBER_AF_MCU
#undef EMBER_AF_MCU
#endif
#define EMBER_AF_MCU EFR32

#ifdef EMBER_AF_MCU_FULL
#undef EMBER_AF_MCU_FULL
#endif
#define EMBER_AF_MCU_FULL EFR32BG1B232F256GM32

#ifdef EMBER_AF_MCU_FAMILY
#undef EMBER_AF_MCU_FAMILY
#endif
#define EMBER_AF_MCU_FAMILY B

#ifdef EMBER_AF_MCU_PERFORMANCE
#undef EMBER_AF_MCU_PERFORMANCE
#endif
#define EMBER_AF_MCU_PERFORMANCE B

#ifdef EMBER_AF_MCU_RADIO
#undef EMBER_AF_MCU_RADIO
#endif
#define EMBER_AF_MCU_RADIO 232

#ifdef EMBER_AF_MCU_FLASH
#undef EMBER_AF_MCU_FLASH
#endif
#define EMBER_AF_MCU_FLASH 256K

#ifdef EMBER_AF_MCU_TEMP
#undef EMBER_AF_MCU_TEMP
#endif
#define EMBER_AF_MCU_TEMP G

#ifdef EMBER_AF_MCU_PACKAGE
#undef EMBER_AF_MCU_PACKAGE
#endif
#define EMBER_AF_MCU_PACKAGE M

#ifdef EMBER_AF_MCU_PINS
#undef EMBER_AF_MCU_PINS
#endif
#define EMBER_AF_MCU_PINS 32



#endif // __BLE_SOC_CONFIG__
