// This file is generated by Ember Desktop.  Please do not edit manually.
//
//

void emberAfMainPluginsInit(void)
{
}

// Tick function declarations.
void emberAfPluginIdleSleepTickCallback(void);

void emberAfMainPluginsTick(void)
{
  emberAfPluginIdleSleepTickCallback();
}
