// This file is generated by Ember Desktop.  Please do not edit manually.
//
//

// Init function declarations.
void hidInit(void);

void emberAfMainPluginsInit(void)
{
  hidInit();
}

// Tick function declarations.
void emberAfPluginIdleSleepTickCallback(void);

void emberAfMainPluginsTick(void)
{
  emberAfPluginIdleSleepTickCallback();
}
