/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#include <stdint.h>
#include "bg_gattdb_def.h"

#ifdef __GNUC__
#define GATT_HEADER(F) F __attribute__ ((section (".gatt_header"))) 
#define GATT_DATA(F) F __attribute__ ((section (".gatt_data"))) 
#else
#ifdef __ICCARM__
#define GATT_HEADER(F) _Pragma("location=\".gatt_header\"") F 
#define GATT_DATA(F) _Pragma("location=\".gatt_data\"") F 
#else
#define GATT_HEADER(F) F 
#define GATT_DATA(F) F 
#endif
#endif

GATT_DATA(const uint16_t bg_gattdb_uuidtable_16_map [])=
{
    0x2800,
    0x2801,
    0x2803,
    0x1800,
    0x2a00,
    0x2a01,
    0x180a,
    0x2a29,
    0x2a24,
    0x2a25,
    0x2a27,
    0x2a26,
    0x2a28,
    0x2a23,
    0x2a2a,
    0x2a50,
    0x1812,
    0x2a4d,
    0x2908,
    0x2a4b,
    0x2a4a,
    0x2a4c,
    0x2a22,
    0x2a32,
    0x2a4e,
    0x2902,
};

GATT_DATA(const uint8_t bg_gattdb_uuidtable_128_map [])=
{
    0x0 //IAR workaround for empty array
};




uint8_t bg_gattdb_attribute_field_47_data[1]={0x01,};
GATT_DATA(const struct bg_gattdb_attribute_chrvalue	bg_gattdb_attribute_field_47 ) = {
	.properties=0x06,
	.index=7,
	.max_len=1,
	.data=bg_gattdb_attribute_field_47_data,
};

GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_46 ) = {
	.len=5,
	.data={0x06,0x30,0x00,0x4e,0x2a,}
};
uint8_t bg_gattdb_attribute_field_45_data[21];
GATT_DATA(const struct bg_gattdb_attribute_chrvalue	bg_gattdb_attribute_field_45 ) = {
	.properties=0x0e,
	.index=6,
	.max_len=20,
	.data_varlen=(struct bg_gattdb_buffer_with_len*)bg_gattdb_attribute_field_45_data,
};

GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_44 ) = {
	.len=5,
	.data={0x0e,0x2e,0x00,0x32,0x2a,}
};
uint8_t bg_gattdb_attribute_field_42_data[21];
GATT_DATA(const struct bg_gattdb_attribute_chrvalue	bg_gattdb_attribute_field_42 ) = {
	.properties=0x12,
	.index=5,
	.max_len=20,
	.data_varlen=(struct bg_gattdb_buffer_with_len*)bg_gattdb_attribute_field_42_data,
};

GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_41 ) = {
	.len=5,
	.data={0x12,0x2b,0x00,0x22,0x2a,}
};
uint8_t bg_gattdb_attribute_field_40_data[1]={0x00,};
GATT_DATA(const struct bg_gattdb_attribute_chrvalue	bg_gattdb_attribute_field_40 ) = {
	.properties=0x04,
	.index=4,
	.max_len=1,
	.data=bg_gattdb_attribute_field_40_data,
};

GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_39 ) = {
	.len=5,
	.data={0x04,0x29,0x00,0x4c,0x2a,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_38 ) = {
	.len=4,
	.data={0x00,0x01,0x00,0x02,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_37 ) = {
	.len=5,
	.data={0x02,0x27,0x00,0x4a,0x2a,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_36 ) = {
	.len=63,
	.data={0x05,0x01,0x09,0x06,0xa1,0x01,0x05,0x07,0x19,0xe0,0x29,0xe7,0x15,0x00,0x25,0x01,0x75,0x01,0x95,0x08,0x81,0x02,0x95,0x01,0x75,0x08,0x81,0x01,0x95,0x05,0x75,0x01,0x05,0x08,0x19,0x01,0x29,0x05,0x91,0x02,0x95,0x01,0x75,0x03,0x91,0x01,0x95,0x06,0x75,0x08,0x15,0x00,0x25,0x65,0x05,0x07,0x19,0x00,0x29,0x65,0x81,0x00,0xc0,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_35 ) = {
	.len=5,
	.data={0x02,0x25,0x00,0x4b,0x2a,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_34 ) = {
	.len=2,
	.data={0x00,0x03,}
};
uint8_t bg_gattdb_attribute_field_33_data[21];
GATT_DATA(const struct bg_gattdb_attribute_chrvalue	bg_gattdb_attribute_field_33 ) = {
	.properties=0x0a,
	.index=3,
	.max_len=20,
	.data_varlen=(struct bg_gattdb_buffer_with_len*)bg_gattdb_attribute_field_33_data,
};

GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_32 ) = {
	.len=5,
	.data={0x0a,0x22,0x00,0x4d,0x2a,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_31 ) = {
	.len=2,
	.data={0x00,0x02,}
};
uint8_t bg_gattdb_attribute_field_30_data[21];
GATT_DATA(const struct bg_gattdb_attribute_chrvalue	bg_gattdb_attribute_field_30 ) = {
	.properties=0x0e,
	.index=2,
	.max_len=20,
	.data_varlen=(struct bg_gattdb_buffer_with_len*)bg_gattdb_attribute_field_30_data,
};

GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_29 ) = {
	.len=5,
	.data={0x0e,0x1f,0x00,0x4d,0x2a,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_28 ) = {
	.len=2,
	.data={0x00,0x01,}
};
uint8_t bg_gattdb_attribute_field_26_data[21];
GATT_DATA(const struct bg_gattdb_attribute_chrvalue	bg_gattdb_attribute_field_26 ) = {
	.properties=0x12,
	.index=1,
	.max_len=20,
	.data_varlen=(struct bg_gattdb_buffer_with_len*)bg_gattdb_attribute_field_26_data,
};

GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_25 ) = {
	.len=5,
	.data={0x12,0x1b,0x00,0x4d,0x2a,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_24 ) = {
	.len=2,
	.data={0x12,0x18,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_23 ) = {
	.len=7,
	.data={0x01,0xff,0xff,0xff,0xff,0xff,0xff,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_22 ) = {
	.len=5,
	.data={0x02,0x18,0x00,0x50,0x2a,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_21 ) = {
	.len=2,
	.data={0xff,0xff,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_20 ) = {
	.len=5,
	.data={0x02,0x16,0x00,0x2a,0x2a,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_19 ) = {
	.len=8,
	.data={0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_18 ) = {
	.len=5,
	.data={0x02,0x14,0x00,0x23,0x2a,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_17 ) = {
	.len=4,
	.data={0x66,0x66,0x66,0x66,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_16 ) = {
	.len=5,
	.data={0x02,0x12,0x00,0x28,0x2a,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_15 ) = {
	.len=4,
	.data={0x66,0x66,0x66,0x66,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_14 ) = {
	.len=5,
	.data={0x02,0x10,0x00,0x26,0x2a,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_13 ) = {
	.len=4,
	.data={0x66,0x66,0x66,0x66,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_12 ) = {
	.len=5,
	.data={0x02,0x0e,0x00,0x27,0x2a,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_11 ) = {
	.len=4,
	.data={0x66,0x66,0x66,0x66,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_10 ) = {
	.len=5,
	.data={0x02,0x0c,0x00,0x25,0x2a,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_9 ) = {
	.len=3,
	.data={0x31,0x2e,0x30,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_8 ) = {
	.len=5,
	.data={0x02,0x0a,0x00,0x24,0x2a,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_7 ) = {
	.len=12,
	.data={0x53,0x69,0x6c,0x69,0x63,0x6f,0x6e,0x20,0x4c,0x61,0x62,0x73,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_6 ) = {
	.len=5,
	.data={0x02,0x08,0x00,0x29,0x2a,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_5 ) = {
	.len=2,
	.data={0x0a,0x18,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_4 ) = {
	.len=1,
	.data={0x00,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_3 ) = {
	.len=5,
	.data={0x02,0x05,0x00,0x01,0x2a,}
};
uint8_t bg_gattdb_attribute_field_2_data[7]={0x42,0x47,0x30,0x30,0x30,0x30,0x30,};
GATT_DATA(const struct bg_gattdb_attribute_chrvalue	bg_gattdb_attribute_field_2 ) = {
	.properties=0x0a,
	.index=0,
	.max_len=7,
	.data=bg_gattdb_attribute_field_2_data,
};

GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_1 ) = {
	.len=5,
	.data={0x0a,0x03,0x00,0x00,0x2a,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_0 ) = {
	.len=2,
	.data={0x00,0x18,}
};
GATT_DATA(const struct bg_gattdb_attribute bg_gattdb_attributes_map[])={
    {.uuid=0x0000,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_0},
    {.uuid=0x0002,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_1},
    {.uuid=0x0004,.permissions=0x803,.datatype=0x01,.min_key_size=0x00,.dynamicdata=&bg_gattdb_attribute_field_2},
    {.uuid=0x0002,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_3},
    {.uuid=0x0005,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_4},
    {.uuid=0x0000,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_5},
    {.uuid=0x0002,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_6},
    {.uuid=0x0007,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_7},
    {.uuid=0x0002,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_8},
    {.uuid=0x0008,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_9},
    {.uuid=0x0002,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_10},
    {.uuid=0x0009,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_11},
    {.uuid=0x0002,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_12},
    {.uuid=0x000a,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_13},
    {.uuid=0x0002,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_14},
    {.uuid=0x000b,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_15},
    {.uuid=0x0002,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_16},
    {.uuid=0x000c,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_17},
    {.uuid=0x0002,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_18},
    {.uuid=0x000d,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_19},
    {.uuid=0x0002,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_20},
    {.uuid=0x000e,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_21},
    {.uuid=0x0002,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_22},
    {.uuid=0x000f,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_23},
    {.uuid=0x0000,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_24},
    {.uuid=0x0002,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_25},
    {.uuid=0x0011,.permissions=0x801,.datatype=0x02,.min_key_size=0x00,.dynamicdata=&bg_gattdb_attribute_field_26},
    {.uuid=0x0019,.permissions=0x807,.datatype=0x03,.min_key_size=0x00,.configdata={.flags=0x01,.index=0x01}},
    {.uuid=0x0012,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_28},
    {.uuid=0x0002,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_29},
    {.uuid=0x0011,.permissions=0x807,.datatype=0x02,.min_key_size=0x00,.dynamicdata=&bg_gattdb_attribute_field_30},
    {.uuid=0x0012,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_31},
    {.uuid=0x0002,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_32},
    {.uuid=0x0011,.permissions=0x803,.datatype=0x02,.min_key_size=0x00,.dynamicdata=&bg_gattdb_attribute_field_33},
    {.uuid=0x0012,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_34},
    {.uuid=0x0002,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_35},
    {.uuid=0x0013,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_36},
    {.uuid=0x0002,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_37},
    {.uuid=0x0014,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_38},
    {.uuid=0x0002,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_39},
    {.uuid=0x0015,.permissions=0x804,.datatype=0x01,.min_key_size=0x00,.dynamicdata=&bg_gattdb_attribute_field_40},
    {.uuid=0x0002,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_41},
    {.uuid=0x0016,.permissions=0x801,.datatype=0x02,.min_key_size=0x00,.dynamicdata=&bg_gattdb_attribute_field_42},
    {.uuid=0x0019,.permissions=0x807,.datatype=0x03,.min_key_size=0x00,.configdata={.flags=0x01,.index=0x05}},
    {.uuid=0x0002,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_44},
    {.uuid=0x0017,.permissions=0x807,.datatype=0x02,.min_key_size=0x00,.dynamicdata=&bg_gattdb_attribute_field_45},
    {.uuid=0x0002,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_46},
    {.uuid=0x0018,.permissions=0x805,.datatype=0x01,.min_key_size=0x00,.dynamicdata=&bg_gattdb_attribute_field_47},
};

GATT_DATA(const uint16_t bg_gattdb_attributes_dynamic_mapping_map[])={
	0x0003,
	0x001b,
	0x001f,
	0x0022,
	0x0029,
	0x002b,
	0x002e,
	0x0030,
};

GATT_DATA(const uint8_t bg_gattdb_adv_uuid16_map[])={0x12, 0x18, };
GATT_DATA(const uint8_t bg_gattdb_adv_uuid128_map[])={0x0};
GATT_HEADER(const struct bg_gattdb_def bg_gattdb_data )={
    .attributes=bg_gattdb_attributes_map,
    .attributes_max=48,
    .uuidtable_16_size=26,
    .uuidtable_16=bg_gattdb_uuidtable_16_map,
    .uuidtable_128_size=0,
    .uuidtable_128=bg_gattdb_uuidtable_128_map,
    .attributes_dynamic_max=8,
    .attributes_dynamic_mapping=bg_gattdb_attributes_dynamic_mapping_map,
    .adv_uuid16=bg_gattdb_adv_uuid16_map,
    .adv_uuid16_num=1,
    .adv_uuid128=bg_gattdb_adv_uuid128_map,
    .adv_uuid128_num=0,
};

const struct bg_gattdb_def *bg_gattdb=&bg_gattdb_data;
