/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef BG_GATTDB_H
#define BG_GATTDB_H

#include "bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define gattdb_device_name                      3
#define gattdb_hid_keyboard_in                 27
#define gattdb_hid_keyboard_out                31
#define gattdb_hid_keyboard_feature            34
#define gattdb_hid_control                     41
#define gattdb_hid_boot_keyboard_in            43
#define gattdb_hid_boot_keyboard_out           46
#define gattdb_hid_protocol_mode               48

#endif
