// This file is generated by Ember Desktop.  Please do not edit manually.
//

#include "boards.h"

#include CONFIGURATION_HEADER
#include CALLBACKS_HEADER

/* standard library headers */
#include <stdint.h>
#include <stdio.h>
#include <stdbool.h>


/* BG stack headers */
#include "bg_types.h"
#include "native_gecko.h"

/* application specific files */
#include "app.h"
#include "app_ui.h"
#include "platform_hw-callback.h"
#include "app-callback.h"

/***********************************************************************************************//**
 *  \brief  Ok To Sleep.
 *  \details  This function is called by the Idle/Sleep plugin before sleeping. It is called with
 *  interrupts disabled. The application should return TRUE if the device may sleep or FALSE
 *  otherwise.
 *  \param  durationMs  The maximum duration in milliseconds that the device will sleep.
 *  \return  true  if it is Ok to sleep.
 **************************************************************************************************/
bool emberAfPluginIdleSleepOkToSleepCallback(uint32_t durationMs)
{
  return true;
}


/***********************************************************************************************//**
 *  \brief  Wake Up.
 *  \details  This function is called by the Idle/Sleep plugin after sleeping.
 *  \param  durationMs  The duration in milliseconds that the device slept.
 **************************************************************************************************/
void emberAfPluginIdleSleepWakeUpCallback(uint32_t durationMs)
{
}


/** @brief Main Stack Init on EFR32
 *
 * This function is called when the stack on the EFR32 starts and can be used to perform necessary
 * initialization required at system startup.
 */
void emberAfMainEfr32StackInitCallback(void)
{
  mainEfr32StackInitCallback();
}



/** @brief Main Application Init on EFR32
 *
 * This function is called when the application on the EFR32 starts and can be used to perform any
 * additional initialization required at system startup.
 */
void emberAfMainEfr32AppInitCallback(void) {

}


/** @brief Main Stack Init on Host
 *
 * This function is called when the stack on the Host starts and can be used to perform necessary
 * initialization required at system startup.
 */
int emberAfMainHostStackInitCallback(int argc, char* argv[]) {
  return 0;
}


/** @brief Main Application Init on Host
 *
 * This function is called when the application on the host starts and can be used to perform any
 * additional initialization required at system startup.
 */
void emberAfMainHostAppInitCallback(void) {
}


/** @brief Main Stack Tick
 *
 * This function is called in each iteration of the main stack loop and
 * can be used to perform periodic functions.  The frequency with which this
 * function is called depends on how quickly the main loop runs.  If the
 * application blocks at any time during the main loop, this function will not
 * be called until execution resumes.  On SoC platforms, sleeping and idling
 * will block.  On Unix hosts, process yielding (e.g., via select) will block.
 */
void emberAfMainStackTickCallback(void) {
}



/** @brief Main Application Tick
 *
 * This function is called in each iteration of the main application loop and
 * can be used to perform periodic functions.  The frequency with which this
 * function is called depends on how quickly the main loop runs.  If the
 * application blocks at any time during the main loop, this function will not
 * be called until execution resumes.  On SoC platforms, sleeping and idling
 * will block.  On Unix hosts, process yielding (e.g., via select) will block.
 */
void emberAfMainAppTickCallback(void) {
	 mainAppTickCallback();
}


void emberAfPluginResetEventCallback(void)
{
  resetEventCallback();
}


