// This file is generated by Ember Desktop.  Please do not edit manually.
//
//

// Enclosing macro to prevent multiple inclusion
#ifndef __BLE_SOC_CONFIG__
#define __BLE_SOC_CONFIG__




// Top level macros
#define SILABS_AF_DEVICE_NAME "ble-soc"


// Generated plugin macros

// Use this macro to check if Bluetooth Smart Demo Application plugin is included
#define SILABS_AF_PLUGIN_APP

// Use this macro to check if Bluetooth Smart Demo Application Hardware Abstraction plugin is included
#define SILABS_AF_PLUGIN_APP_HW

// Use this macro to check if Idle/Sleep plugin is included
#define SILABS_AF_PLUGIN_IDLE_SLEEP
// User options for plugin Idle/Sleep
#define SILABS_AF_PLUGIN_IDLE_SLEEP_MINIMUM_DURATION_MS 5

// Use this macro to check if Bluetooth Smart Platform plugin is included
#define SILABS_AF_PLUGIN_PLATFORM

// Use this macro to check if Bluetooth Smart Platform Hardware Abstraction plugin is included
#define SILABS_AF_PLUGIN_PLATFORM_HW


// Generated API headers

// API app_hw from Bluetooth Smart Demo Application Hardware Abstraction plugin
#define SILABS_AF_API_APP_HW "../../../../../SiliconLabs/BluetoothSmartSDK/1.0.2.0-GA/sdk/plugins/app_hw/app_hw.h"


// Custom macros
#ifdef EMBER_AF_RADIO
#undef EMBER_AF_RADIO
#endif
#define EMBER_AF_RADIO EFR32

#ifdef EMBER_AF_RADIO_FULL
#undef EMBER_AF_RADIO_FULL
#endif
#define EMBER_AF_RADIO_FULL EFR32BG1B232F256GM32

#ifdef EMBER_AF_RADIO_FAMILY
#undef EMBER_AF_RADIO_FAMILY
#endif
#define EMBER_AF_RADIO_FAMILY B

#ifdef EMBER_AF_RADIO_PERFORMANCE
#undef EMBER_AF_RADIO_PERFORMANCE
#endif
#define EMBER_AF_RADIO_PERFORMANCE B

#ifdef EMBER_AF_RADIO_RADIO
#undef EMBER_AF_RADIO_RADIO
#endif
#define EMBER_AF_RADIO_RADIO 232

#ifdef EMBER_AF_RADIO_FLASH
#undef EMBER_AF_RADIO_FLASH
#endif
#define EMBER_AF_RADIO_FLASH 256K

#ifdef EMBER_AF_RADIO_TEMP
#undef EMBER_AF_RADIO_TEMP
#endif
#define EMBER_AF_RADIO_TEMP G

#ifdef EMBER_AF_RADIO_PACKAGE
#undef EMBER_AF_RADIO_PACKAGE
#endif
#define EMBER_AF_RADIO_PACKAGE M

#ifdef EMBER_AF_RADIO_PINS
#undef EMBER_AF_RADIO_PINS
#endif
#define EMBER_AF_RADIO_PINS 32

#ifdef EMBER_AF_MCU
#undef EMBER_AF_MCU
#endif
#define EMBER_AF_MCU EFR32

#ifdef EMBER_AF_MCU_FULL
#undef EMBER_AF_MCU_FULL
#endif
#define EMBER_AF_MCU_FULL EFR32BG1B232F256GM32

#ifdef EMBER_AF_MCU_FAMILY
#undef EMBER_AF_MCU_FAMILY
#endif
#define EMBER_AF_MCU_FAMILY B

#ifdef EMBER_AF_MCU_PERFORMANCE
#undef EMBER_AF_MCU_PERFORMANCE
#endif
#define EMBER_AF_MCU_PERFORMANCE B

#ifdef EMBER_AF_MCU_RADIO
#undef EMBER_AF_MCU_RADIO
#endif
#define EMBER_AF_MCU_RADIO 232

#ifdef EMBER_AF_MCU_FLASH
#undef EMBER_AF_MCU_FLASH
#endif
#define EMBER_AF_MCU_FLASH 256K

#ifdef EMBER_AF_MCU_TEMP
#undef EMBER_AF_MCU_TEMP
#endif
#define EMBER_AF_MCU_TEMP G

#ifdef EMBER_AF_MCU_PACKAGE
#undef EMBER_AF_MCU_PACKAGE
#endif
#define EMBER_AF_MCU_PACKAGE M

#ifdef EMBER_AF_MCU_PINS
#undef EMBER_AF_MCU_PINS
#endif
#define EMBER_AF_MCU_PINS 32



#endif // __BLE_SOC_CONFIG__
